{% set name = "fluidfft-builder" %}
{% set version = "0.0.3" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fluidfft_builder-{{ version }}.tar.gz
  sha256: 7cd4bb179a17e9f636aabcdc36429a75a16d2122eb507df8c4873aa7a15e71a5

build:
  entry_points:
    - fluidfft-builder-make-file = fluidfft_builder.make_cy_files:main
    - fluidfft-builder-print-include-dir = fluidfft_builder:print_include_dir
    - fluidfft-builder-print-include-dir-cython = fluidfft_builder:print_include_dir_cython
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - fluidfft_builder
  commands:
    - pip check
    # cannot be tested here...
    # - fluidfft-builder-make-file --help
    - fluidfft-builder-print-include-dir
    - fluidfft-builder-print-include-dir-cython
  requires:
    - pip

about:
  summary: Fluidfft plugin dependencies
  license: MIT
  license_file: LICENSE
  home: https://fluidfft.readthedocs.io

extra:
  recipe-maintainers:
    - paugier
